# Importer les librairies

In [2]:
import pandas as pd 
# IMPORTER LES LIBRAIRIES NECESSAIRES A L'ETUDE

# Importer les données

In [4]:
data = pd.read_csv("Data/MK8_Dataset.csv", sep=";")
data

,Date,Challenger,Round,Pts,Elo,Rank,Game_phase,Tier,Year,Company,Top_player,Months_after_left_company
0,20211006,Ilir,1,37,1016,2,1-Early,B,2021,Trivadis,1,NaN
1,20211006,Alex,1,27,952,4,1-Early,C,2021,Trivadis,1,-19.0
2,20211006,Sylvain,1,29,984,3,1-Early,C,2021,Trivadis,0,NaN
3,20211006,Sacha,1,54,1048,1,1-Early,S,2021,Trivadis,1,-27.0
4,20211006,Ilir,2,48,1029,2,1-Early,A,2021,Trivadis,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2104,20250410,Alex,11,37,946,3,3-Late,B,2025,Trivadis,1,23.0
2105,20250410,Lev,12,48,1370,1,3-Late,A,2025,Trivadis,1,12.0
2106,20250410,Luca,12,47,1340,2,3-Late,A,2025,Trivadis,1,NaN
2107,20250410,Martin,12,44,1136,3,3-Late,A,2025,Trivadis,1,NaN
2108,20250410,Denes,12,43,1199,4,3-Late,A,2025,Accenture,1,NaN

In [5]:
data.describe()

,Date,Round,Pts,Elo,Rank,Year,Top_player,Months_after_left_company
count,2.109000e+03,2109.000000,2109.000000,2109.000000,2109.000000,2109.000000,2109.000000,1140.000000
mean,2.023067e+07,7.096254,42.133713,1095.514936,2.575628,2022.996207,0.821242,-5.963158
std,1.052761e+04,4.360502,8.860619,197.834988,1.313553,1.067008,0.383240,11.804690
min,2.021101e+07,1.000000,10.000000,607.000000,1.000000,2021.000000,0.000000,-30.000000
25%,2.022100e+07,4.000000,37.000000,946.000000,1.000000,2022.000000,1.000000,-15.000000
50%,2.023070e+07,7.000000,43.000000,1091.000000,2.000000,2023.000000,1.000000,-6.000000
75%,2.024042e+07,10.000000,49.000000,1243.000000,3.000000,2024.000000,1.000000,2.000000
max,2.025041e+07,26.000000,60.000000,1612.000000,8.000000,2025.000000,1.000000,23.000000

# Questions

Le résultat de la function doit vous donner exactement le tableau ci-dessous.

## 1. Inférence statistique (4 pts)

**Q1: Le score moyen en Pts de Sacha est différent de celui de la moyenne de tous les matchs joués? Qu'en est-il de celui des autres top players?**

=> z-test echantillon parties de Sacha vs moyenne de la population et stdev de la population. 

DISCUSSION. Calculer ensuite les z-score de tous les top player et identifier ceux qui sortent de la moyenne. Calculer les d de Cohen pour quantifier la taille d'effet.
(Ceci est un bon exercice pour manipuler les numpy array)

**Q2: Le score moyen en Pts de Sacha est différent de celui de Lev?**

=> t-test à deux échantillons entre Sacha et Lev. Calculer le d de Cohen pour quantifier taille d'effet.

DISCUSSION. Quid de Lev et son némesis Luca ? (filtre sur 2023, 2024 et 2025, on cherche un cas ou la différence n'est pas significative)

**Q3: Est-ce que les joueurs d'Accenture se retrouvent autant dans chaque Tier que les joueurs de Trivadis?**

=> Test de Chi-carré Tier x Company (filtre sur Trivadis, Accenture car sinon le test n'est pas valide)

DISCUSSION. Quels sont les odds ratio par Tier pour Trivadis vs Accenture? Interprétez vos analyses.

**Q4: Existe-t-il une relation entre les Pts et le score Elo?**

=> Test de corrélation entre Pts et Elo.

DISCUSSION. Calculer le R carré. Quelle part de variance des Pts est expliquée par le score Elo? Interprétez ce résultat, i.e. qu'est-ce que cela veut dire pour quelqu'un qui a un grand score Elo?

**INSTRUCTIONS**

Pour chacune des questions 1 à 4 ci-dessus, argumenter de manière statistique en effectuant chacune des étapes suivantes:
1. Identifier la ou les variables d'intérêt et spécifier le type.
2. Réaliser une visualisation appropriée selon la ou les variables.
3. Enoncer une hypothèse nulle et une hypothèse alternative considérant la ou les variables identifiées.
4. Identifier le test statistique approprié selon les hypothèses énoncées.
5. Vérifier la validation des assumptions selon le test identifié.
6. Calculer la statistique ainsi que la p-valeur.
7. Prendre une décision à partir de la p-valeur et d'un seuil alpha de 5%.
8. Interpréter le résultat et évaluer la taille de l'effet.

Quelques liens utiles pour la taille de l'effet:
* [https://rpsychologist.com/cohend/](https://rpsychologist.com/cohend/)
* [https://datatab.net/tutorial/effect-size-independent-t-test](https://datatab.net/tutorial/effect-size-independent-t-test)
* [https://www.simplypsychology.org/effect-size.html](https://www.simplypsychology.org/effect-size.html)

## 2. Data mining (2 pts)

**Q1: Effectuer une analyse statistique des personnes qui ont quitté la company à l'aide de la régression linéaire. On cherche à prédire la variable dépendante `Elo` à l'aide des variables indépendantes `Challenger` et `Months_after_left_company`. Interpréter les coefficients et discuter de leur importance statistique en vous appuyant sur leur p-valeur. Faites une visualisation pour illustrer le phénomène.**

**Q2: Effecter une analyse statistique à l'aide d'un arbre de classification avec comme variable dépendante `Tier` et variables indépendantes `Elo`, `Company`, `Game_phase`. Fixer une profondeur maximale de 4. Visualiser l'arbre et expliquer quelques décisions.**